[package]
name = "build-agent"
version.workspace = true
edition.workspace = true

[dependencies]
lambda_runtime.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build.dependencies]
proto-gen = { path = "../proto_gen" }
