[package]
name = "dto"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
prost.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
stock-trek.workspace = true

[build-dependencies]
proto-gen = { path = "../proto_gen" }
