[package]
name = "proto-gen"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
prost.workspace = true
protoc-bin-vendored.workspace = true
serde.workspace = true

[build-dependencies]
prost.workspace = true
prost-types.workspace = true
prost-build.workspace = true
