name: Build master and update lambda

on:
  push:
    branches: master

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get secrets
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "fafecebc-b41d-496d-915f-5ce536a6644b"
          project-slug: "aws"
          env-slug: "prod"

      - name: Get secrets
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "fafecebc-b41d-496d-915f-5ce536a6644b"
          project-slug: "publish"
          env-slug: "prod"

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        env:
          GITHUB_APP_CREATE_TAGS_CLIENT_ID: ${{ env.GITHUB_APP_CREATE_TAGS_CLIENT_ID }}
          GITHUB_APP_CREATE_TAGS_PRIVATE_KEY: ${{ env.GITHUB_APP_CREATE_TAGS_PRIVATE_KEY }}
        with:
          client-id: ${{ env.GITHUB_APP_CREATE_TAGS_CLIENT_ID }}
          private-key: ${{ env.GITHUB_APP_CREATE_TAGS_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-tags: true
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run checks
        run: |
          cargo fmt --check
          cargo clippy
          cargo test
          exit 0

      - name: Get version, check if tag exists, create and publish if not
        id: tags
        env:
          AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          VERSION=$(cargo pkgid --package build-agent | rev | cut -d '@' -f 1 | cut -d '#' -f 1 | rev)
          IMAGE_PREFIX="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/build-agent"
          GIT_TAG="v${VERSION}"
          if git ls-remote --tags origin "refs/tags/${GIT_TAG}" | grep -q "refs/tags/${GIT_TAG}"; then
            echo "Tag ${GIT_TAG} already exists"
            exit 0
          else
            echo "Creating tag ${GIT_TAG}"
            git config user.name "github-actions[bot]"
            git config user.email 'CreateTags[bot]@users.noreply.github.com'
            git tag "${GIT_TAG}"
            git push origin "${GIT_TAG}"
            echo "image-master=${IMAGE_PREFIX}:master" >> $GITHUB_OUTPUT
            echo "image-versioned=${IMAGE_PREFIX}:${VERSIONED}" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        env:
          AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ROLE_UPDATE_LAMBDA_BUILD_AGENT_RUST: ${{ env.AWS_ROLE_UPDATE_LAMBDA_BUILD_AGENT_RUST }}
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_UPDATE_LAMBDA_BUILD_AGENT_RUST }}"
          role-session-name: "build-agent-${{ github.run_id }}"
          retry-max-attempts: 3
          mask-aws-account-id: true

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx (required for caching)
        uses: docker/setup-buildx-action@v4

      - name: Build and push with cache
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ steps.tags.outputs.image-master }}
            ${{ steps.tags.outputs.image-versioned }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

      # Use EC2 instead
      # - name: Update lambda to use latest image from master
      #   env:
      #     AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
      #     AWS_REGION: ${{ env.AWS_REGION }}
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name stock-trek-compile-rust \
      #       --image-uri "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/algorithm-compiler:master"
