pub const SUCCESS: i32 = 0;

// strategy errors
pub const STRATEGY_NOT_FOUND: i32 = 1001;
pub const STRATEGY_HAS_NO_CONSTRUCTOR: i32 = 1002;
pub const STRATEGY_COULD_NOT_INSTANTIATE: i32 = 1003;

// server errors
pub const SERVER_ENTRY_INCORRECT_ARG_COUNT: i32 = 2001;
pub const SERVER_ENTRY_FAILED_TO_PARSE_COMMAND: i32 = 2002;
pub const SERVER_ENTRY_FAILED_TO_CONVERT_TO_JSON: i32 = 2003;
pub const SERVER_ENTRY_FAILED_TO_SET_LINKED_FUNCTION: i32 = 2004;
pub const SERVER_ENTRY_FAILED_TO_FIND_LINKED_FUNCTION: i32 = 2005;
pub const SERVER_ENTRY_FAILED_TO_ENQUEUE_JSON: i32 = 2006;

pub const SERVER_RUNNER_STRATEGY_CONTEXT_FILE_NOT_FOUND: i32 = 2101;
pub const SERVER_RUNNER_STRATEGY_CONTEXT_NOT_DECODED: i32 = 2102;
pub const SERVER_RUNNER_STRATEGY_CONTEXT_NOT_CREATED: i32 = 2103;

pub const SERVER_RUNNER_PORTFOLIO_FILE_NOT_FOUND: i32 = 2201;
pub const SERVER_RUNNER_PORTFOLIO_NOT_DECODED: i32 = 2202;
pub const SERVER_RUNNER_PORTFOLIO_NOT_CREATED: i32 = 2203;

pub const SERVER_RUNNER_CONNECTION_FAILED: i32 = 2301;

// bot errors
pub const BOT_ERROR_CREATING_RESOLVER: i32 = 3001;
pub const BOT_ERROR_CREATING_SCRATCH_PAD: i32 = 3002;
pub const BOT_ERROR_RESOLVING_ACTION: i32 = 3003;
